server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: ecommerce-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sahaja_swalayan_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type: trace

# Email Configuration
email:
  provider: ${EMAIL_PROVIDER:mailtrap}  # Options: mailtrap, sendgrid, ses, smtp
  from:
    address: ${EMAIL_FROM_ADDRESS:noreply@sahajaswalayan.com}
    name: ${EMAIL_FROM_NAME:Sahaja Swalayan}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012}
  expiration: ${JWT_EXPIRATION:86400000} # 1 day in milliseconds

# Mailtrap Email Configuration
mailtrap:
  api:
    token: ${MAILTRAP_API_TOKEN:be6c841a60f2b9d55b25c3561ac05db9}
  sandbox:
    enabled: ${MAILTRAP_SANDBOX_ENABLED:true}
    inbox-id: ${MAILTRAP_SANDBOX_INBOX_ID:3906683}

# Xendit Payment Gateway Configuration
xendit:
  api-key: ${XENDIT_API_KEY:xnd_development_q8X7XhaSMHiXC5yxNKi1r7IZlG6lO4ki03Uk2Tf5KUOWB5pile5q6xlGX617Bd}
  base-url: ${XENDIT_BASE_URL:https://api.xendit.co}
  success-redirect-url: ${XENDIT_SUCCESS_REDIRECT_URL:https://yourdomain.com/payment/success}
  callback-token: ${XENDIT_CALLBACK_TOKEN:cb_token_livekey_9xsWcG5XEwLj2DcZxDq7P0vJxngE1bW28m6V1CulTzr0JVqP7V}

# Application Configuration
app:
  confirmation:
    base-url: ${APP_CONFIRMATION_BASE_URL:http://localhost:8080/api/v1/auth/confirm}

logging:
  level:
    com.sahaja.swalayan.ecommerce: DEBUG