server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: ecommerce-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sahaja_swalayan_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type: trace
  cache:
    type: caffeine
    cache-names: default
    caffeine:
      spec: maximumSize=500,expireAfterWrite=24h

# Email Configuration
email:
  provider: ${EMAIL_PROVIDER:resend}  # Options: mailtrap, resend, sendgrid, ses, smtp
  from:
    address: ${EMAIL_FROM_ADDRESS:noreply@sahajaswalayan.com}
    name: ${EMAIL_FROM_NAME:Sahaja Swalayan}

# Resend Email Configuration
resend:
  api:
    key: ${RESEND_API_KEY:re_GgoVidMg_GfExt9eZZHoy2bdpy5jgSRBq}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012}
  expiration: ${JWT_EXPIRATION:86400000} # 1 day in milliseconds

# Mailtrap Email Configuration
mailtrap:
  api:
    token: ${MAILTRAP_API_TOKEN:be6c841a60f2b9d55b25c3561ac05db9}
  sandbox:
    enabled: ${MAILTRAP_SANDBOX_ENABLED:true}
    inbox-id: ${MAILTRAP_SANDBOX_INBOX_ID:3906683}

# Xendit Payment Gateway Configuration
xendit:
  api-key: ${XENDIT_API_KEY:xnd_development_q8X7XhaSMHiXC5yxNKi1r7IZlG6lO4ki03Uk2Tf5KUOWB5pile5q6xlGX617Bd}
  base-url: ${XENDIT_BASE_URL:https://api.xendit.co}
  success-redirect-url: ${XENDIT_SUCCESS_REDIRECT_URL:http://localhost:3000/orders/success}
  callback-token: ${XENDIT_CALLBACK_TOKEN:KPKnvU0mpkfmOr3CUByM9slnusn2pydxV2ndUCDeXSpcuzwh}

# Biteship Shipping API Configuration
biteship:
  api-key: ${BITESHIP_API_KEY:biteship_test.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidG9rZW4yQXVndXN0MjAyNSIsInVzZXJJZCI6IjY4ODk1OGFjZDUzNDAyMDAxMjEyNDIzZiIsImlhdCI6MTc1NDE0MjkwMH0.ldmRCss83tQmqc6vhomF-dMowTz9rkjLqFt01lsLGJo}
  base-url: ${BITESHIP_BASE_URL:https://api.biteship.com}

# Application Configuration
app:
  confirmation:
    base-url: ${APP_CONFIRMATION_BASE_URL:http://localhost:8080/api/v1/auth/confirm}

logging:
  level:
    com.sahaja.swalayan.ecommerce: DEBUG

# Shipping Origin (Warehouse) Configuration
shipping:
  webhook:
    token: KPKnvU0mpkfmOr3CUByM9slnusn2pydxV2ndUCDeXSpcuzwh
    url: https://d7e206864e30.ngrok-free.app/api/v1/shipping/webhook
  stub:
    enabled: true  # set to false to use real Biteship integration
  origin:
    contact-name: ${SHIPPING_ORIGIN_CONTACT_NAME:Sahaja Warehouse}
    contact-phone: ${SHIPPING_ORIGIN_CONTACT_PHONE:+621234567890}
    contact-email: ${SHIPPING_ORIGIN_CONTACT_EMAIL:warehouse@sahajaswalayan.com}
    organization: ${SHIPPING_ORIGIN_ORGANIZATION:Sahaja Swalayan}
    address: ${SHIPPING_ORIGIN_ADDRESS:Jalan Warehouse No. 1, Jakarta}
    note: ${SHIPPING_ORIGIN_NOTE:Main warehouse}
    postal-code: ${SHIPPING_ORIGIN_POSTAL_CODE:10110}
    area-id: ${SHIPPING_ORIGIN_AREA_ID:ID-JKT-10000}
    location-id: ${SHIPPING_ORIGIN_LOCATION_ID:}
    collection-method: ${SHIPPING_ORIGIN_COLLECTION_METHOD:pickup}
    latitude: ${SHIPPING_ORIGIN_LATITUDE:-6.200000}
    longitude: ${SHIPPING_ORIGIN_LONGITUDE:106.816666}